### ISSUE TITLE
Chart text not visible when dark theme

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/citizen-directory#77]
Adjust the font color in the charts at https://citizens.nation3.org to make the text visible when dark theme.

Light theme:

> ![](https://github.com/user-attachments/assets/d6e841ac-5214-42c6-ad4f-ffec3ca4b5fe)

Dark theme:

> ![](https://github.com/user-attachments/assets/a65de40a-78bf-44a8-9fdb-d47f25bd0885)

**Comment by SankhaChak** [comment]
PR - https://github.com/nation3/citizen-directory/pull/78 should fix this issue

**Comment by aahna-ashina** [comment]
#78
